### ISSUE TITLE
Roadmap towards 0.5

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#653]
The UI has finally been released as stable (Gekko v0.4.5). For 0.5 I want to focus on bringing more features to the UI, fixing bugs and stabilising the APIs.

This is what I am thinking about:

- [x] UI live gekko
  - [x] show list of trades (see #693)
  - [x] finalise profit reporting *(well not finalised, but good enough for now)*
- [ ] live trader: see PR #737
- [x] adapters
  - [x] ~~stabilise adapter API~~ pushed to 0.6..
  - [x] fix widely used adapters
    - [x] sqlite
    - [x] postgresql
- [ ] ~~stabilise web API~~ pushing this to 0.6
  - [ ] ~~stabilise REST API (without merging default config)~~
  - [ ] ~~document REST & WS APIs~~

If anyone has any other ideas, please put them in a **seperate** issue and link that issue here. I am obviously also open to PRs :)

**Comment by tuxitor** [comment]
A couple of ideas about live configuration changes are asked for here #654

**Comment by thegamecat** [comment]
It would be really nice to be able to flow through indicators to the charting tool. 

At the moment I have to write out the indicator outputs plus price / meta to a csv then plot it all in excel. Which is time consuming.

**Comment by askmike** [comment]
Great point, I was thinking about this as well. Something like #690 maybe? (Let's keep discussion in there).

**Comment by thegamecat** [comment]
Would be good to be able to have a "update data" button that updated each (or selected) currency pair up to yesterday.

**Comment by askmike** [comment]
I am closing already this as I am planning on merging #737 very soon (hopefully this weekend). That issue holds details of the last minor things.
